#ifndef __EPD_H_
#define __EPD_H_

#include "Debug.h"
//#include "utility/EPD_1in02.h"
//#include "utility/EPD_1in54.h"
//#include "utility/EPD_1in54_V2.h"
//#include "utility/EPD_1in54b.h"
//#include "utility/EPD_1in54b_V2.h"
//#include "utility/EPD_1in54c.h"
//#include "utility/EPD_1in64g.h"
//#include "utility/EPD_2in7.h"
//#include "utility/EPD_2in7_V2.h"
//#include "utility/EPD_2in7b.h"
//#include "utility/EPD_2in7b_V2.h"
//#include "utility/EPD_2in9.h"
//#include "utility/EPD_2in9_V2.h"
//#include "utility/EPD_2in9bc.h"
//#include "utility/EPD_2in9b_V3.h"
//#include "utility/EPD_2in9d.h"
//#include "utility/EPD_2in13.h"
//#include "utility/EPD_2in13_V2.h"
//#include "utility/EPD_2in13_V3.h"
//#include "utility/EPD_2in13_V4.h"
//#include "utility/EPD_2in13bc.h"
//#include "utility/EPD_2in13b_V3.h"
//#include "utility/EPD_2in13b_V4.h"
//#include "utility/EPD_2in13d.h"
//#include "utility/EPD_2in13g.h"
//#include "utility/EPD_2in36g.h"
//#include "utility/EPD_2in66.h"
//#include "utility/EPD_2in66b.h"
//#include "utility/EPD_2in66g.h"
//#include "utility/EPD_3in0g.h"
//#include "utility/EPD_3in7.h"
//#include "utility/EPD_3in52.h"
//#include "utility/EPD_4in01f.h"
//#include "utility/EPD_4in2.h"
//#include "utility/EPD_4in2_V2.h"
//#include "utility/EPD_4in2bc.h"
//#include "utility/EPD_4in2b_V2.h"
//#include "utility/EPD_4in26.h"
//#include "utility/EPD_4in37g.h"
#include "EPD_5in65f.h"
#include "EPD_5in65f.cpp"
// #include "utility/EPD_5in83.h"
// #include "utility/EPD_5in83_V2.h"
// #include "utility/EPD_5in83bc.h"
// #include "utility/EPD_5in83b_V2.h"
// #include "utility/EPD_7in3g.h"
// #include "utility/EPD_7in3f.h"
// #include "utility/EPD_7in5.h"
// #include "utility/EPD_7in5_V2.h"
// #include "utility/EPD_7in5bc.h"
// #include "utility/EPD_7in5b_V2.h"
// #include "utility/EPD_7in5_HD.h"
// #include "utility/EPD_7in5b_HD.h"
// #include "utility/EPD_13in3k.h"

#endif
